### ISSUE TITLE
Typo in page 111

### ISSUE THREAD

**Issue by sunnyjiahui** [EricDarve/numerical_linear_algebra#11]
At the last line, I guess it should be $O(r n^2)$

**Comment by EricDarve** [comment]
I think I was being a bit pedantic here.

<img width="137" alt="screen shot 2017-10-17 at 2 09 12 pm" src="https://user-images.githubusercontent.com/4644566/31689591-c5c376ce-b344-11e7-97b8-ea1c054d79fe.png">

Are you referring to this? It's Omega instead of O. It means that this is both an upper and lower bound.

**Comment by sunnyjiahui** [comment]
Yes, it is.  thank you for the explanation.
