### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by manon643** [EricDarve/numerical_linear_algebra#111]
In the course reader, Chapter 10 Section 2 paragraph after Sparse Right hand side, it's written "we have that both L and b are sparse". It should be x instead of b as a sparse b is the hypothesis. 

In the review hand-out, 10.6.2 the indexes for l_{ji} are switched.

**Comment by EricDarve** [comment]
Thanks for l_{ji}. That was an error.

For your first comment, the sentence should be read that we have something special because both L and b are sparse. Logically we have A sparse implies L sparse. But b is mentioned as well because the combination of both L and b means we need a new algorithm. b was stated before but it's recalled in the statement because it is key.
