### ISSUE TITLE
Potential clarification needed on Pg.200

### ISSUE THREAD

**Issue by Zan-AA** [EricDarve/numerical_linear_algebra#154]
On Pg. 200, the statement
![image](https://user-images.githubusercontent.com/41386609/68436692-92900400-0173-11ea-9972-c5387523f95c.png)
claims that A is upper triangular if x=0. However, given the definition of A in the previous page,
![image](https://user-images.githubusercontent.com/41386609/68436714-9e7bc600-0173-11ea-9eba-18782bbabfdc.png)
A is lower triangular instead.

I believe the statement meant to be talking about the modified A after one-step of single-shift QR iteration
![image](https://user-images.githubusercontent.com/41386609/68436835-05997a80-0174-11ea-80b0-d9cff807d96a.png)
which is indeed upper triangular if x=0.

Perhaps another notation such as A^1 or A_1 or simply "the modified matrix" could be used to avoid this confusion? (correspondingly, the notation used for a_21 on the same page should be modified as well for consistency)

**Comment by EricDarve** [comment]
Thanks. Actually what we meant is that A is lower triangular. So z is exactly an eigenvalue. Hence the shift is exact and we immediately converge. This case is a little weird (hence the error in the text) because we think of A as converging to an upper triangular matrix. However if A is lower triangular, we also get an exact shift. And as you are pointing out, A becomes upper triangular after one step of the QR iteration.

I fixed the notation for a_21. I added ^qr so it is clear that this is not the original A but A after one step of the QR iteration.
