### ISSUE TITLE
Potential clarification needed - page 229

### ISSUE THREAD

**Issue by gradeyw** [EricDarve/numerical_linear_algebra#157]
I don't think going from the LHS to the RHS of this equation relies on the upper Hessenberg structure of H (so I don't think "Because H is upper Hessenberg" is necessary)

![image](https://user-images.githubusercontent.com/55860296/68446373-5a97b980-0191-11ea-8e57-e93aa1a500c7.png)

**Comment by EricDarve** [comment]
You do need H to be upper Hessenberg. It's not easy to see. f is a polynomial of degree k. We are only interested in the first column of f(H). Take H^2. Since H is upper Hessenberg the first column of H^2 only involves the first 2 columns of H:
[H^2](i,1) = sum_{k=1}^2 H(i,k) H(k,1)
Similarly with H^3, we only need the first 3 columns of H. And so on. So if f is a polynomial of degree k f(H) only depends on the first k columns and therefore this is the same as H_k. This is how you can prove that the first k rows, col 1 of f(H) match those of f(H_k).

This does not hold for a general matrix A.
