### ISSUE TITLE
Some typos in the course reader

### ISSUE THREAD

**Issue by nmbader** [EricDarve/numerical_linear_algebra#197]
The following is only tentative, they may not need a fix or correction:
1) p.18-19: vector a_i in R^n but the matrix A is m x n, maybe a_i should be in R^m
2) p.22: "If the rows of V^{-1} are w1,...,wn"   missing transpose
3) p.23: "Now we can consider the **basis** B with entries"     **basis <- matrix**
4) p.51: "This polynomial has smaller degree than the **minimal polynomial** of A." **minimal polynomial <- characteristic polynomial**
5) p.101: caption of figure 4.5: "This shows that our implementation of pivoted LU **as** the same..."    **as <- has**
6) p.107: "...which is much better than the **\Omega**(rn^2)..."   **\Omega <- O**
7) p. 108: in the code, the condition <if A[k,k] != 0> may not be fulfilled because of round-off error and the code will run all the way to 'n'; maybe a threshold is needed.
8) p.172: "It will turn out that **can do** Step 2"   **can do <- we can do**
9) p.186: "This makes sense because Tk is converging to a **diagonal** matrix..."  **diagonal <- upper triangular**
10) p.187: "Here, since **T-\mu_I** is a complex matrix"    **T-/mu_I <- T-\mu I**
11) p.204: "Picking the shift is a bit easier this time since B^TB is symmetric positive **definite**"  **definite <- semi-definite**
12) p.227: "This might be **2** in Figure 7.1"    **2 <- true**
13) p.261: In the last inequality, the absolute value should be added to qk(lambda)
14) p.349: "... each **time time** we "factor" out a node..."   duplicate word **time**
15) p.368: "**If** a notebook, you can try to type..."    **If <- In**
16) p.377: "The function **eig** returns both"   **eig <- eigen**

**Comment by EricDarve** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Correct
5. Fixed
6. Omega is correct here. It's a small point really. https://www.geeksforgeeks.org/analysis-of-algorithms-set-3asymptotic-notations/ Omega denotes a lower bound. Basically "at least".
7. We assume we did a rook pivoting to find the pivot. So the pivot is large compared to other entries. Still if all entries that were found are exactly zero, the algorithm fails. We could test for very small entries as well if we are looking for an early termination. Because of rook pivoting though, machine roundoff errors remain small and the algorithm is stable.
8. Fixed
9. Correct. It's only diagonal in the symmetric case.
10. Thanks. Weird typo.
11. Yes.
12. It's 2. We are referring to lambda_1 = 2 in Fig. 7.1.
13. Thanks. There were a couple of additional errors in these pages; notably the condition number of X was missing.
14. Fixed
15. Fixed
16. Fixed. I also added a mention of eigvals and eigvecs.

Thank you for all these corrections.
