### ISSUE TITLE
Inconsistent notation in Figure 10.8, Page 260

### ISSUE THREAD

**Issue by yhl-icme** [EricDarve/numerical_linear_algebra#52]
On the top of the bottom figure 10.8, the notation of the row sub-trees is $T^1$, which is different from $J^i$ in the context.

--
Honglin Yuan

**Comment by EricDarve** [comment]
That's a font problem actually. Both characters are \mathcal T in Latex, but the figure was done using a "regular" Latex font while the body text uses a different font. I will fix that but it will take time since I need to redo the figure. It looks like J but it's a calligraphic T actually. 

Not a great character font actually. It's hard to believe this is a T.

**Comment by EricDarve** [comment]
<img width="689" alt="screen shot 2017-12-13 at 11 30 08 am" src="https://user-images.githubusercontent.com/4644566/33958359-07497464-dff9-11e7-95a4-659143c31465.png">

That's a T on the left and J on the right.
