### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by QiuyeJia** [EricDarve/numerical_linear_algebra#61]
The course reader said to type "julia> Pkg.add("IJulia") to start. But on my computer, it did not work.
I found another way on https://github.com/JuliaLang/IJulia.jl   

which tells me to write 
using Pkg
Pkg.add("IJulia")

and it worked.  (By the way, I used Windows 10).

Another thing is that, when I was installing Jupyter, the command "jupyter notebook" can not work in the commander and I am confused where to  type it.

Then I turned to the python way of installation. I installed python 3.7.0 before but the python 3 command did not work:
python3 -m pip install --upgrade pip
python3 -m pip install jupyter

 

Then I tried the command wrote for python 2 :
python -m pip install --upgrade pip
python -m pip install jupyter

and it worked, I am confused.

I think the instructor has used macOS throughout the process of writing this book. Maybe it would be better to test those instructions and on Windows see if they work  since many people are using Windows.

**Comment by cwalker4** [comment]
Apologies to the repo owners if this isn't the right forum for this discussion, but a few tips that might help:

- You have to bring modules into scope with either `using` or `import` – the book doesn't always include these lines, possibly because it would get very redundant very fast. See [this](https://docs.julialang.org/en/stable/manual/modules/) for details.

- You don't actually type `julia>`before your commands – when you launch Julia (via the command line or by double-clicking), it opens an interactive session in your CLI, for which `julia>` is the prompt. See [here](https://docs.julialang.org/en/v0.6.1/manual/getting-started/) for some examples. 

- I highly recommend the Anaconda distribution of Python – it comes with Python, Jupyter, and many other common packages for scientific computing and data science. On Windows it comes with the additional benefit of Anaconda Prompt, which is a much, _much_ cleaner way of interacting with Python on Windows than trying to wrangle with Command Prompt. I imagine it would solve your problem. 

- If you're having trouble launching Jupyter via the command line, you probably have to set up your system path so your command prompt knows where your Python library (including the `jupyter notebook` executable) lives. Alternatively, `pip` may not have installed Jupyter in the right place. See the discussions [here](https://stackoverflow.com/questions/41034866/running-jupyter-via-command-line-on-windows) and [here](https://stackoverflow.com/questions/35313876/after-installing-with-pip-jupyter-command-not-found) for discussion and tips. You won't have to worry about this if you use Anaconda.

**Comment by EricDarve** [comment]
@cwalker4 Thanks for the feedback. I will incorporate. You are a student in CME 302 (or you have no idea what I am talking about)?

**Comment by cwalker4** [comment]
@EricDarve I am! Though my comment was more for addressing @QiuyeJia’s specific issues than suggestions for the book.

**Comment by cwalker4** [comment]
@QiuyeJia If you're a CME 302 student the course Piazza page would be a better forum for these questions – this space is for reporting issues with the book. 

But to answer your question, the colon `:` in Julia can be used to create a `Range` object, which doesn't print as an `Array` would (i.e. you get back your `Range` instead of all the elements). If you want to look at the elements of a range as an array, you can use `collect()`.  Try running the code below.

```Julia
a = 1.0:0.1:2.0  # initialize a range

@show a
@show typeof(a)
@show collect(a)
@show typeof(collect(a))
```

**Comment by QiuyeJia** [comment]
@cwalker4    I am talking about my confusion as a reader, which is a part topics related to the book.

**Comment by QiuyeJia** [comment]
@cwalker4 I am talking about my confusion as a reader, which is a part of topics related to the book.

**Comment by EricDarve** [comment]
@cwalker4 Thanks for the answers. This helps. 

@QiuyeJia Yes, some of these questions are better suited on piazza where they can benefit everyone and you have more people who can help you.

Regarding some of the points you are raising in your original post, some of it has to do with Julia v1.0. For example, using Pkg is something "new" that previously was not required.

I understand your frustration with the other issues with jupyter and Python but I did not plan on covering that in the book. Installation instructions for this software should be found online.
